---
- name: secure ssh
  include_tasks: security.yml
  tags:
    - init
    - security

- name: create ssh directory
  file:
    path: "~{{ item.username }}/.ssh"
    state: directory
    owner: "{{ item.username }}"
    group: "{{ item.username }}"
    mode: 0700
  with_items:
    - "{{ users }}"
  become: yes
  tags:
    - init

- name: generate SSH key
  openssh_keypair:
    path: "~{{ item.username }}/.ssh/id_rsa"
    owner: "{{ item.username }}"
  with_items:
    - "{{ users }}"
  become: yes
  tags:
    - init

- name: install acl package to allow ownership change
  apt:
    name: acl
    state: present
  become: yes
  when:
    - ansible_user_id != "root"
    - ansible_distribution == "Ubuntu"

- name: add github keys to known hosts
  known_hosts:
    path: "~{{ item.0.username }}/.ssh/known_hosts"
    name: github.com
    key: "{{ item.1 }}"
    state: present
  with_nested:
    - "{{ users }}"
    - "{{ github_host_keys }}"
  become: yes
  become_user: "{{ item.0.username }}"
  tags:
    - init

- name: add bitbucket keys to known hosts
  known_hosts:
    path: "~{{ item.0.username }}/.ssh/known_hosts"
    name: bitbucket.org
    key: "{{ item.1 }}"
    state: present
  with_nested:
    - "{{ users }}"
    - "{{ bitbucket_host_keys }}"
  become: yes
  become_user: "{{ item.0.username }}"
  tags:
    - init
