---
- name: ssh hardening
  include_role:
    name: dev-sec.ssh-hardening
    apply:
      become: yes
  vars:
    - sftp_enabled: true

    # "no real advantage without denied shell access":
    - ssh_allow_tcp_forwarding: true
    - ssh_allow_agent_forwarding: true
  tags:
    - security
