---
- name: update repositories index
  apt:
    update_cache: true
  become: yes
  when: ansible_distribution == "Ubuntu"
  tags:
    - update_apt_index

- name: install useful packages for Ubuntu
  apt:
    name: "{{ recommended_ubuntu_packages }}"
    state: present
  become: yes
  when: ansible_distribution == "Ubuntu"

- name: setup NTP
  import_tasks: ntp.yml
  when: ansible_distribution == "Ubuntu"

- name: set swap partition
  import_tasks: swap.yml
