---
- name: update repositories index
  apt:
    update_cache: true
  become: true
  when: ansible_facts["distribution"] == "Ubuntu"
  tags:
    - update_apt_index

- name: install useful packages for Ubuntu
  apt:
    name: "{{ recommended_ubuntu_packages }}"
    state: present
  become: true
  when: ansible_facts["distribution"] == "Ubuntu"

- name: setup NTP
  import_tasks: ntp.yml
  when:
    - ansible_facts["distribution"] == "Ubuntu"
    - ansible_facts["distribution_version"] is version("24.04", "<")
