---
certbot_admin_email: "dev@magnet.cl"
nginx_headers:
# Use the default list from the role:
  # avoid clickjacking
  - X-Frame-Options SAMEORIGIN
  # disable content-type sniffing
  - X-Content-Type-Options nosniff
  # XSS filter
  - X-XSS-Protection "1; mode=block"
  - Strict-Transport-Security max-age=15768000
# But disable this one as it makes CDNs hard to use:
  # - Content-Security-Policy "script-src 'self'; object-src 'self'"
