---
- hosts: all
  vars_prompt:
    - name: magnet_username
      prompt: "Enter your Magnet username (as in username@magnet.cl, without the @magnet.cl domain) to add as authorized key"
      private: no
  tasks:
    - name: get github username
      uri:
        url: "{{ intranet_url }}"
        return_content: yes
      register: intranet_response
      vars:
        intranet_url: "https://intranet.magnet.cl/api/1.0/github-user/{{ magnet_username }}/"

    - name: fail if github username is not defined
      fail:
        msg: "The github username is not defined"
      when: "not intranet_response.json.github_username"

    - name: authorize ssh key
      authorized_key:
        user: "{{ ansible_user_id }}"
        state: present
        key: "https://github.com/{{ github_username }}.keys"
      vars:
        github_username: "{{ intranet_response.json.github_username }}"

    - name: check if mothership scout is present
      stat:
        path: mothership_scout/scout.py
      register: mothership_scout_path

    - name: report ssh keys to mothership if able
      command: python3 mothership_scout/scout.py --report-keys
      when: mothership_scout_path.stat.exists
