---
- hosts: all
  vars_prompt:
    - name: magnet_username
      prompt: "Enter user (user@magnet.cl) to deauthorize"
      private: no
  tasks:
    - name: get github username
      uri:
        url: "{{ intranet_url }}"
        return_content: yes
      register: intranet_response
      vars:
        intranet_url: "https://intranet.magnet.cl/api/1.0/github-user/{{ magnet_username }}/"
      delegate_to: localhost

    - name: fail if github username is not defined
      fail:
        msg: "The github username is not defined"
      when: "not intranet_response.json.github_username"
      delegate_to: localhost

    - name: deauthorize ssh key
      authorized_key:
        user: "{{ ansible_user_id }}"
        state: absent
        key: "https://github.com/{{ github_username }}.keys"
      vars:
        github_username: "{{ intranet_response.json.github_username }}"
