---
- hosts: localhost
  roles:
    - role: common
    - role: zsh
      vars:
        users:
          - username: "{{ ansible_user_id }}"
      tags:
        - utils
        - zsh
    - role: vim
      vars:
        users:
          - username: "{{ ansible_user_id }}"
      tags:
        - utils
        - vim
