---
- hosts: localhost
  vars:
    do_access_token: "{{ lookup('env', 'DIGITALOCEAN_ACCESS_TOKEN') }}"

  vars_prompt:
    - name: domain
      prompt: "Enter domain"
      default: "do.magnet.cl"
      private: no
    - name: hostname
      prompt: "Enter hostname for A record (without domain)"
      private: no
    - name: ip
      prompt: "Enter ip for A record"
      private: no

  tasks:
    - name: check if digital ocean token env var is set
      assert:
        that: "lookup('env', 'DIGITALOCEAN_ACCESS_TOKEN')"
        fail_msg: "DIGITALOCEAN_ACCESS_TOKEN must be set"

    - name: gather digital ocean account info
      digital_ocean_account_info:
        oauth_token: "{{ do_access_token }}"
      register: account_info

    - name: print account info
      debug:
        var: account_info

    - name: register hostname in Digital Ocean DNS with doctl
      command:
        argv:
          - doctl
          - compute
          - domain
          - records
          - create
          - --record-type
          - A
          - --record-name
          - "{{ hostname }}"
          - --record-data
          - "{{ ip }}"
          - --record-ttl
          - 3600
          - "{{ domain }}"
      register: result
      changed_when: result.rc == 0
