---
- name: use geerlingguy role to install docker
  hosts: all
  roles:
    - role: geerlingguy.docker
      become: yes
      vars:
        docker_install_compose: false         # Don't install standalone binary, which is now not recommended
        docker_install_compose_plugin: true   # Use the plugin instead
        docker_users:
          - "{{ ansible_user_id }}"
  tasks:
    - name: show hint
      debug:
        msg: Done. Please reboot so you can use docker without sudo (or just reconnect if using ssh).
