---
- name: vps init
  hosts: all
  vars:
    github_users_as_initial_admins:  # TODO get list dinamically
      - imunizaga
      - wooo-
      - nstuardod

  vars_prompt:
    - name: std_user
      prompt: "Enter user name to create a standard user without sudo"
      default: magnet
      private: false
    - name: std_user_password
      prompt: "Enter user password"
      private: true
      encrypt: "sha512_crypt"
      confirm: true

    - name: admin_user
      prompt: "Enter user name to create an administrator with sudo"
      default: magnet-admin
      private: false
    - name: admin_user_password
      prompt: "Enter administrator password"
      private: true
      encrypt: "sha512_crypt"
      confirm: true

    - name: server_name
      prompt: Server name
      private: false
    - name: server_environment
      prompt: |-
        Server environment
          - DEVELOPMENT
          - QA
          - PRODUCTION
          - OTHER
        choose from the list above
      private: false
      default: DEVELOPMENT
    - name: project_code
      prompt: Project code
      private: false
    - name: known_domain_name
      prompt: Known domain name
      private: false

  pre_tasks:
    - name: obtain token for Mothership from env var
      set_fact:
        has_mothership_token: '{{ lookup("env", "MOTHERSHIP_USER_KEY") != "" }}'

    - name: check that ansible_limit is defined
      assert:
        that: ansible_limit is defined
        fail_msg: Please explicitly limit the hosts you want to target with --limit or -l
        quiet: yes

    - name: set default locale
      lineinfile:
        path: /etc/environment
        regexp: "^LC_ALL="
        line: "LC_ALL=\"{{ default_locale | default('en_US.UTF-8') }}\""
      become: yes
      tags:
        - init

  roles:
    - role: users
      tags:
        - init
      vars:
        std_username: "{{ std_user }}"
        std_password: "{{ std_user_password }}"
        admin_username: "{{ admin_user }}"
        admin_password: "{{ admin_user_password }}"
        initial_admin_gh_names: "{{ github_users_as_initial_admins }}"
    - role: ssh
      tags:
        - init
      vars:
        users:
          - username: "{{ std_user }}"
          - username: "{{ admin_user }}"
    - role: common
      tags:
        - init
    - role: zsh
      vars:
        users:
          - username: "{{ std_user }}"
          - username: "{{ admin_user }}"
      tags:
        - init
        - utils
        - zsh
    - role: vim
      vars:
        users:
          - username: "{{ std_user }}"
          - username: "{{ admin_user }}"
      tags:
        - init
        - utils
        - vim

  post_tasks:
    - name: set ntp pool
      include_role:
        name: common
        tasks_from: set_ntp_pool
      when:
        - ansible_distribution == "Ubuntu"
        - ansible_distribution_version is version("24.04", "<")
    - name: set swap partition
      include_role:
        name: common
        tasks_from: set_swap
    - name: upgrade packages
      apt:
        upgrade: safe
      become: yes
      when: ansible_distribution == "Ubuntu"
    - name: install Mothership's scout
      include_role:
        name: mothership_scout
      vars:
        server_payload:
          name: '{{ server_name }}'
          environment: '{{ server_environment }}'
          project_code: '{{ project_code }}'
          known_domain_names: ['{{ known_domain_name }}']
          last_known_ip_address: '{{ ansible_facts["default_ipv4"]["address"] }}'
      tags:
        - init
        - mothership
      when: has_mothership_token
