---
- name: add python-apt (package_facts dependency on Ubuntu)
  apt:
    name: python-apt
    state: present
  become: yes
  when: ansible_distribution == "Ubuntu"
  tags:
    - certbot

- name: gather package facts to check if nginx is installed
  package_facts:
    manager: auto

- name: add certbot ppa
  apt_repository:
    repo: 'ppa:certbot/certbot'
    codename: bionic
    state: present
  become: yes
  when:
    - "'nginx' in ansible_facts.packages"
    -  ansible_distribution == "Ubuntu"
  tags:
    - certbot

- name: install certbot and nginx plugin
  apt:
    name:
      - certbot
      - python-certbot-nginx
  become: yes
  when:
    - "'nginx' in ansible_facts.packages"
    -  ansible_distribution == "Ubuntu"
  tags:
    - certbot

- name: generate certificate for the current host through the nginx plugin
  command:
    argv:
      - certbot
      - --nginx
      - --non-interactive
      - --agree-tos
      - --redirect
      - -m {{ certbot_admin_email }}
      - -d {{ ansible_host.split('@') | last }}
  become: yes
  when: "'nginx' in ansible_facts.packages"
  tags:
    - certbot

- name: secure nginx
  include_tasks: security.yml
  when: "'nginx' in ansible_facts.packages"
  tags:
    - certbot
