- name: harden nginx configuration
  include_role:
    name: devsec.hardening/devsec.hardening/roles/nginx_hardening
    apply:
      become: yes
  vars:
    - nginx_add_header: "{{ nginx_headers }}"
    - nginx_owner_group: "{{ ansible_real_group_id }}"
    - nginx_dh_size: "2048"
